/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

import com.mycompany.edittraininfo.Database;
import com.mycompany.edittraininfo.Employee;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.*;
import java.io.*;
import java.lang.System.Logger;
import java.util.*;
import java.awt.event.WindowAdapter;
import javax.imageio.ImageIO;
import javax.swing.*;


/**
 *
 * @author KARTHI
 */
public class AddAdmin extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form Registration
     */
    FileInputStream input;
    int c=0;
    Calendar cal;
    String adminid;
    String adminpassword;
      PreparedStatement preparedStatement;
    File imageFile;
    String id,pin;
    String Passname;
    String Passid;
    String Age;
    String Emailid;
    String firstname;
    String lastname;
    String occupation;
    String State;
    String City;
    String fathername;
    String mothername;
    String gender;
    String DOB;
    String address;
    String district;
   String Mobileno;
    String aadharno;
    String TDOB;
    String Pincode;
    Connection con;
    public AddAdmin()  throws SQLException {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        Fathersname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Mothername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mobileno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Occupation = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        adharno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pincode = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Button = new javax.swing.JButton();
        Cityname = new javax.swing.JTextField();
        Female = new javax.swing.JRadioButton();
        BtuunDOB = new javax.swing.JButton();
        Limage = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TdateOB = new javax.swing.JTextField();
        BupImg = new javax.swing.JButton();
        idlabel = new javax.swing.JLabel();
        adminpass = new javax.swing.JLabel();
        rtypepass = new javax.swing.JLabel();
        AdminPasssword = new javax.swing.JPasswordField();
        retypeadminpassword = new javax.swing.JPasswordField();
        adminidget = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocation(new java.awt.Point(1300, 1200));
        setSize(new java.awt.Dimension(2000, 1000));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("                                                              REGISTRATION FORM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 10, 820, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FIRST NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 120, 30);

        FirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName);
        FirstName.setBounds(160, 110, 210, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 100, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("FATHER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 130, 30);

        LastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(LastName);
        LastName.setBounds(640, 100, 250, 30);

        Fathersname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fathersname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FathersnameActionPerformed(evt);
            }
        });
        getContentPane().add(Fathersname);
        Fathersname.setBounds(160, 170, 210, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("MOTHER NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 170, 140, 30);

        Mothername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mothername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MothernameActionPerformed(evt);
            }
        });
        getContentPane().add(Mothername);
        Mothername.setBounds(640, 160, 250, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("AGE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 90, 30);

        age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(age);
        age.setBounds(160, 230, 210, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("DATE OF BIRTH");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 270, 140, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("EMAIL ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 280, 120, 30);

        emailid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });
        getContentPane().add(emailid);
        emailid.setBounds(160, 280, 210, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("MOBILE NUMBER");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 320, 160, 30);

        mobileno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoActionPerformed(evt);
            }
        });
        getContentPane().add(mobileno);
        mobileno.setBounds(640, 310, 250, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("OCCUPATION");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 340, 130, 30);

        Occupation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccupationActionPerformed(evt);
            }
        });
        getContentPane().add(Occupation);
        Occupation.setBounds(160, 342, 210, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("AADHAR NUMBER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 360, 170, 30);

        adharno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adharno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharnoActionPerformed(evt);
            }
        });
        getContentPane().add(adharno);
        adharno.setBounds(640, 360, 250, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("STATE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 400, 130, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TAMILNADU", "DELHI", "KERALA", "ANDHERA", "MATHIYAPRADEESH", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 400, 210, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("DISTRICT");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 400, 130, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIRUDHUNAGAR", "MADURAI", "SIVAKASI", "THOOTHUKUDI", "TRUNELVELI", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(640, 400, 250, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("CITY");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 460, 130, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("PIN CODE");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(460, 450, 140, 30);

        pincode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodeActionPerformed(evt);
            }
        });
        getContentPane().add(pincode);
        pincode.setBounds(640, 450, 250, 30);

        Submit.setBackground(new java.awt.Color(0, 102, 51));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(550, 620, 170, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("ADDRESS");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1050, 360, 140, 40);

        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        getContentPane().add(Address);
        Address.setBounds(990, 410, 280, 80);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("GENDER");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(460, 220, 140, 30);

        Male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Male.setText("MALE");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male);
        Male.setBounds(640, 210, 100, 40);

        Button.setBackground(new java.awt.Color(0, 102, 255));
        Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setText("Back");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Button);
        Button.setBounds(330, 620, 160, 40);

        Cityname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cityname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitynameActionPerformed(evt);
            }
        });
        getContentPane().add(Cityname);
        Cityname.setBounds(160, 460, 210, 30);

        Female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Female.setText("FEMALE");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female);
        Female.setBounds(740, 210, 130, 40);

        BtuunDOB.setText("Select");
        BtuunDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtuunDOBActionPerformed(evt);
            }
        });
        getContentPane().add(BtuunDOB);
        BtuunDOB.setBounds(850, 250, 40, 40);
        cal  =new Calendar(TdateOB );
        cal.frame.setVisible(false);

        Limage.setBackground(new java.awt.Color(153, 153, 153));
        Limage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(Limage);
        Limage.setBounds(1000, 60, 190, 220);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Max. Image Size : Less than (1MB)");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(1000, 290, 190, 15);

        TdateOB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TdateOBPropertyChange(evt);
            }
        });
        getContentPane().add(TdateOB);
        TdateOB.setBounds(650, 260, 180, 30);

        BupImg.setText("Upload Image");
        BupImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupImgActionPerformed(evt);
            }
        });
        getContentPane().add(BupImg);
        BupImg.setBounds(1040, 320, 110, 23);

        idlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        idlabel.setText("Your Admin Id ");
        getContentPane().add(idlabel);
        idlabel.setBounds(10, 530, 180, 30);

        adminpass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminpass.setText("Your Admin Password");
        getContentPane().add(adminpass);
        adminpass.setBounds(420, 500, 200, 40);

        rtypepass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtypepass.setText("Retype Password");
        getContentPane().add(rtypepass);
        rtypepass.setBounds(460, 540, 150, 30);

        AdminPasssword.setText("jPasswordField1");
        getContentPane().add(AdminPasssword);
        AdminPasssword.setBounds(650, 502, 230, 30);

        retypeadminpassword.setText("jPasswordField2");
        getContentPane().add(retypeadminpassword);
        retypeadminpassword.setBounds(650, 542, 230, 30);

        adminidget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminidgetActionPerformed(evt);
            }
        });
        getContentPane().add(adminidget);
        adminidget.setBounds(200, 522, 180, 40);

        setBounds(0, 0, 1302, 1207);
    }// </editor-fold>                        

    private void FathersnameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
    }                                           

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       
    }                                       

    private void mobilenoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
      
    }                                        

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
       
    }                                         

    private void OccupationActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void MothernameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
       
    }                                          

    private void adharnoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
    }                                       

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }                                        

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        if(evt.getSource() == Button)
        {
            JOptionPane.showMessageDialog(this, "Registration Successfully..","Success",JOptionPane.INFORMATION_MESSAGE);
            Employee u = new Employee();
            u.setVisible(true);
            this.setVisible(false);
        }
        else
        {
           // JOptionPane.showMessageDialog(this, "Registration Successfully..","Success",JOptionPane.INFORMATION_MESSAGE);
        }
    }                                      

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
             
            try{
                id = adminidget.getText();
                 fathername = Fathersname.getText();
                 Emailid = emailid.getText();
                 Age = age.getText();
                 Mobileno = mobileno.getText();
                 mothername = Mothername.getText();
                 firstname = FirstName.getText();
                 lastname = LastName.getText();
                 address = Address.getText();
                 City = Cityname.getText();
                 TDOB = TdateOB.getText();
                 State = (String) jComboBox1.getSelectedItem();
                 district = (String) jComboBox2.getSelectedItem();
                 pin = pincode.getText();
                 occupation = Occupation.getText();
                 aadharno = adharno.getText();
                 char r1[] = AdminPasssword.getPassword();
                String u1 = new String(r1);
               char r2[] = retypeadminpassword.getPassword();
               String u2= new String(r2);
                /* if(u1 != u1)
                 {
                   JOptionPane.showMessageDialog(AddAdmin.this, "Password MisMatch","Error",JOptionPane.ERROR_MESSAGE);  
                 }
                 else*/
                 {
                     char r[] =  AdminPasssword.getPassword();
                     adminpassword = new String(r);
                 }
            if(fathername.isEmpty() || lastname.isEmpty() ||  mothername.isEmpty() || occupation.isEmpty() || district.equals(" ") || City.equals(" ") || address.equals(" ") )
            {
                JOptionPane.showMessageDialog(AddAdmin.this, "Enter all Fields","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
               Database_1 ob = new Database_1();
              // String sql = "INSERT INTO `user_info` (`image_data`) VALUES (?)";
              //  preparedStatement = con.prepareStatement(sql);
              //  preparedStatement.setBinaryStream(1, input, (int)imageFile.length());
              //  preparedStatement.executeUpdate();
               
                 if(Male.isSelected())
                 {
                    gender = "Male";
                 }
                 else
                 {
                     gender = "Female";
                 }
                 String query="insert into admin_info values('"+id+"','"+firstname+"','"+lastname+"','"+fathername+"','"+mothername+"','"+Age+"','"+gender+"','"+TDOB+"','"+Emailid+"','"+occupation+"','"+Mobileno+"','"+aadharno+"','"+State+"','"+district+"','"+City+"','"+pin+"','"+address+"','"+Limage+"','"+adminpassword+"')";
                    int t=ob.execute(query);
		 if(t==0)
		   {
			   JOptionPane.showMessageDialog(this, "Unable To Insert Please try Again Later","Error",JOptionPane.ERROR_MESSAGE);	   
		   }
                 else
			   JOptionPane.showMessageDialog(this, "OPERATION Done your user id is" + id +" Don't Forget","Success",JOptionPane.INFORMATION_MESSAGE);
                           
			
                }
            }
                catch(Exception ex){
                    ex.printStackTrace();
                }
              
    }                                      

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       
    }                                       

    private void CitynameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:\
       
    }                                        

    private void pincodeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       
    }                                       

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
      
    }                                    

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        
    }                                      

    private void BtuunDOBActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
      //  System.out.print("wedfghjk");
      c++;
      
      cal.frame.addWindowListener(new WindowListener(){
          public void windowClosed(WindowEvent w){}
          public void windowOpened(WindowEvent e) {}
          public void windowClosing(WindowEvent e) {c++;}
          public void windowIconified(WindowEvent e) {   }
          public void windowDeiconified(WindowEvent e) {}
          public void windowActivated(WindowEvent e) {}
          public void windowDeactivated(WindowEvent e) {}

       });
        if(c%2==1 && evt.getSource()==BtuunDOB){
                     
            cal.frame.setVisible(true);
            cal.frame.setBounds(670, 330, 400, 300);
                        
        }
        else{
            System.out.print(DOB);
            cal.frame.setVisible(false);
            //TdateOB.setText(DOB);
        }
    }                                        

    private void BupImgActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
      
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imageFile=new File(selectedFile.getPath());
       if(imageFile.length()< 1048576){    
        try {
            input=new FileInputStream(imageFile);
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image image = imageIcon.getImage().getScaledInstance(Limage.getWidth(), Limage.getHeight(), Image.SCALE_DEFAULT);    
            Limage.setIcon(new ImageIcon(image));
            Limage.setVisible(true);
            
          /* String sql = "INSERT INTO `images_table` (image_data,passenger_id) VALUES (?,?)";
                preparedStatement = con.prepareStatement(sql);
                
                preparedStatement.setBinaryStream(1, input, (int) imageFile.length());
                preparedStatement.setString(2, id);
                int x=preparedStatement.executeUpdate();
                 if(x==0)
		   {
			   JOptionPane.showMessageDialog(this, "Unable To Insert Please try Again Later ","Error",JOptionPane.ERROR_MESSAGE);	   
		   }
                 else{
			   JOptionPane.showMessageDialog(this, "OPERATION SUCESSFUL ","Error",JOptionPane.INFORMATION_MESSAGE);	   
                   }
            */    
                
        }catch(Exception ex)
                {
                    ex.printStackTrace();
                }
        }
         else{
                    JOptionPane.showMessageDialog(null, "Image SiZe too Large", "Upload Image", JOptionPane.WARNING_MESSAGE);
                }
        }
       
       
    }                                      

    private void TdateOBPropertyChange(java.beans.PropertyChangeEvent evt) {                                       
        // TODO add your handling code here:
        
    }                                      

    private void adminidgetActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddAdmin().setVisible(true);
                } catch (SQLException ex) {
                   ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Address;
    private javax.swing.JPasswordField AdminPasssword;
    private javax.swing.JButton BtuunDOB;
    private javax.swing.JButton BupImg;
    private javax.swing.JButton Button;
    private javax.swing.JTextField Cityname;
    private javax.swing.JTextField Fathersname;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel Limage;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField Mothername;
    private javax.swing.JTextField Occupation;
    private javax.swing.JButton Submit;
    public javax.swing.JTextField TdateOB;
    private javax.swing.JTextField adharno;
    private javax.swing.JTextField adminidget;
    private javax.swing.JLabel adminpass;
    private javax.swing.JTextField age;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel idlabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobileno;
    private javax.swing.JTextField pincode;
    private javax.swing.JPasswordField retypeadminpassword;
    private javax.swing.JLabel rtypepass;
    // End of variables declaration                   

    private void add(Calendar c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
