/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

import com.mycompany.edittraininfo.Employee;

/**
 *
 * @author myash
 */
public class AdminStatus extends javax.swing.JFrame {

    /**
     * Creates new form AdminStatus
     */
    public AdminStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text = new javax.swing.JLabel();
        TrainView = new javax.swing.JButton();
        UserView = new javax.swing.JButton();
        Reserved = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(null);

        Text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Admin Status");
        Text.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TextMouseMoved(evt);
            }
        });
        getContentPane().add(Text);
        Text.setBounds(312, 22, 416, 54);

        TrainView.setBackground(new java.awt.Color(210, 107, 218));
        TrainView.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TrainView.setText("View");
        TrainView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainViewActionPerformed(evt);
            }
        });
        getContentPane().add(TrainView);
        TrainView.setBounds(66, 178, 215, 54);

        UserView.setBackground(new java.awt.Color(255, 255, 0));
        UserView.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UserView.setText("View");
        UserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserViewActionPerformed(evt);
            }
        });
        getContentPane().add(UserView);
        UserView.setBounds(70, 370, 215, 54);

        Reserved.setBackground(new java.awt.Color(0, 255, 255));
        Reserved.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Reserved.setText("View");
        Reserved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservedActionPerformed(evt);
            }
        });
        getContentPane().add(Reserved);
        Reserved.setBounds(70, 530, 215, 54);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<-<-<- Click To View The Train Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(411, 178, 534, 54);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<-<-<-Click To View User Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 370, 534, 54);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" <-<-<- Click To View The Reserved Member Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 530, 540, 54);

        Back.setBackground(new java.awt.Color(255, 51, 51));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(829, 77, 171, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/Front.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1780, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextMouseMoved

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Employee t = new Employee();
        t.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void TrainViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainViewActionPerformed
        // TODO add your handling code here:
        AdminTrain s = new AdminTrain();
        s.setVisible(true);
       // this.setVisiblie(false);
        
    }//GEN-LAST:event_TrainViewActionPerformed

    private void UserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserViewActionPerformed
        // TOstatusDO add your handling code here:
         UserStatus u = new UserStatus();
        this.setVisible(false);
        u.setVisible(true);
    }//GEN-LAST:event_UserViewActionPerformed

    private void ReservedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservedActionPerformed
        // TODO add your handling code here:
        ReservesStatus u = new ReservesStatus();
        this.setVisible(false);
        u.setVisible(true);
        
    }//GEN-LAST:event_ReservedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Reserved;
    private javax.swing.JLabel Text;
    private javax.swing.JButton TrainView;
    private javax.swing.JButton UserView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
