/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

import com.mycompany.edittraininfo.Employee;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author KARTHI
 */
public class Edit_Traininfo extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Traininfo
     */
    String t_no;
    String t_name;
    String t_from;
    String t_to;
    String arr;
    String des;
    String cost;
    public Edit_Traininfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        trainno = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        arrival = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        departure = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("EDIT TRAIN INFORMATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 10, 850, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("TRAIN NAME ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 140, 180, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("TRAIN NO  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 180, 140, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("FROM ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 250, 150, 50);

        tname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(tname);
        tname.setBounds(560, 140, 260, 40);

        trainno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(trainno);
        trainno.setBounds(560, 200, 260, 40);

        from.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(from);
        from.setBounds(560, 260, 260, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("TO ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 320, 140, 40);

        to.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(to);
        to.setBounds(560, 320, 260, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("ARRIVAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 360, 190, 60);

        arrival.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(arrival);
        arrival.setBounds(560, 372, 260, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("DEPATURE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 426, 160, 40);

        departure.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(departure);
        departure.setBounds(560, 422, 260, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("COST");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 480, 190, 40);

        price.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(price);
        price.setBounds(560, 482, 260, 40);

        Reset.setBackground(new java.awt.Color(255, 255, 0));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset);
        Reset.setBounds(680, 560, 140, 40);

        Back.setBackground(new java.awt.Color(255, 51, 51));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(220, 560, 140, 40);

        Submit.setBackground(new java.awt.Color(0, 102, 51));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(430, 560, 170, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/train/steam-train-chugs-through-mountain-forest-scene-generative-ai.jpg"))); // NOI18N
        jLabel9.setText("BACK");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, -140, 1650, 1170);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 70, 1290, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
       t_no = trainno.getText();
       t_name = tname.getText();
       t_from = from.getText();
       t_to = to.getText();
       arr = arrival.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
       LocalTime time = LocalTime.parse(arr,formatter);
       des = departure.getText();
    //    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
       LocalTime time1 = LocalTime.parse(des,formatter);
       cost = price.getText();
       if(t_no.equals("") || t_name.equals("") || t_from.equals("") || t_to.equals(""))
       {
           JOptionPane.showConfirmDialog(this, "Enter All Fields ", "Error",JOptionPane.ERROR_MESSAGE);
       }
        Pattern p1=Pattern.compile("[0-9]{3,10}");
		Matcher m1=p1.matcher(cost);
		boolean match1=m1.matches();
                if(!match1)
                {
                  JOptionPane.showMessageDialog(this, "Cost is not valid ","Error",JOptionPane.ERROR_MESSAGE);  
                }
       else
       {
           
           String Query = "insert into train_information values('"+t_no+"','"+t_name+"','"+t_from+"','"+t_to+"','"+time+"','"+time1+"','"+cost+"')";
           Database_1 o = new Database_1();
           int yd = o.execute(Query);
               if(yd==0)
		   {
			   JOptionPane.showMessageDialog(this, "Unable To Insert Please try Again Later","Error",JOptionPane.ERROR_MESSAGE);	   
		   }
		   else
			   JOptionPane.showMessageDialog(this, "OPERATION SUCESSFUL ","Error",JOptionPane.INFORMATION_MESSAGE);	 
       }
    }//GEN-LAST:event_SubmitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        String def = " ";
        tname.setText(def);
        trainno.setText(def);
        from.setText(def);
        to.setText(def);
        arrival.setText(def);
        departure.setText(def);
        price.setText(def);
    }//GEN-LAST:event_ResetActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "OPERATION SUCESSFUL ","Error",JOptionPane.INFORMATION_MESSAGE);
         Employee r = new Employee();
         this.setVisible(false);
         r.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Traininfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField arrival;
    private javax.swing.JTextField departure;
    private javax.swing.JTextField from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField price;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField to;
    private javax.swing.JTextField trainno;
    // End of variables declaration//GEN-END:variables
}
