/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.ByteArrayInputStream;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author myash
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    Connection con;
    Statement stmt,stmt1;
    ResultSet result,result1;
    String h1;
    int resid1;
    Icon i2;
   
    public Profile() {
        initComponents();
       
     //  h1 = passid.getText();
       // resid1 = Integer.parseInt(h1);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Genderlabel = new javax.swing.JLabel();
        occupationlabel = new javax.swing.JLabel();
        photolabel = new javax.swing.JLabel();
        passid = new javax.swing.JTextField();
        View = new javax.swing.JButton();
        Tname = new javax.swing.JTextField();
        Tdob = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        Tstate = new javax.swing.JTextField();
        Tdistrict = new javax.swing.JTextField();
        Tcity = new javax.swing.JTextField();
        mobilenolabel = new javax.swing.JTextField();
        genderlabel = new javax.swing.JTextField();
        Toccupation = new javax.swing.JTextField();
        Taddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(485, 20, 92, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 280, 174, 43);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("DOB");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 390, 174, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Email ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 480, 135, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("State");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 590, 135, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("District");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(810, 590, 143, 32);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("City");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 690, 65, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Mobile Number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(143, 916, 179, 32);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(143, 983, 96, 32);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(816, 508, 122, 32);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Passenger ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(47, 112, 161, 35);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Occupation");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(816, 335, 122, 32);
        getContentPane().add(Genderlabel);
        Genderlabel.setBounds(391, 983, 146, 32);
        getContentPane().add(occupationlabel);
        occupationlabel.setBounds(1216, 331, 0, 51);

        photolabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(photolabel);
        photolabel.setBounds(735, 45, 203, 246);
        getContentPane().add(passid);
        passid.setBounds(214, 112, 190, 35);

        View.setBackground(new java.awt.Color(255, 255, 204));
        View.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        View.setText("Press");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        getContentPane().add(View);
        View.setBounds(445, 112, 132, 35);

        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });
        getContentPane().add(Tname);
        Tname.setBounds(370, 280, 223, 47);

        Tdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdobActionPerformed(evt);
            }
        });
        getContentPane().add(Tdob);
        Tdob.setBounds(370, 390, 223, 44);

        Temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemailActionPerformed(evt);
            }
        });
        getContentPane().add(Temail);
        Temail.setBounds(370, 500, 417, 32);
        getContentPane().add(Tstate);
        Tstate.setBounds(390, 590, 184, 32);

        Tdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdistrictActionPerformed(evt);
            }
        });
        getContentPane().add(Tdistrict);
        Tdistrict.setBounds(1020, 590, 233, 38);
        getContentPane().add(Tcity);
        Tcity.setBounds(380, 680, 233, 40);
        getContentPane().add(mobilenolabel);
        mobilenolabel.setBounds(397, 917, 233, 41);
        getContentPane().add(genderlabel);
        genderlabel.setBounds(397, 976, 233, 39);
        getContentPane().add(Toccupation);
        Toccupation.setBounds(1014, 331, 196, 51);

        Taddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaddressActionPerformed(evt);
            }
        });
        getContentPane().add(Taddress);
        Taddress.setBounds(1014, 496, 196, 49);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 20, 160, 40);

        jLabel13.setText("jLabel13");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1290, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
        } catch (SQLException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            
            try {
               // LoginPage u = new LoginPage();
                String query = "SELECT * from user_info ";
                stmt = con.createStatement();
                result = stmt.executeQuery(query);
                    String pname,souce,des,arr,dept,mob,add,agE,fare,tno,time,cno,ctyp,styp,sno,fp,fi,fi1;
                    Integer resid;
                    if(result.next()){
                        resid = result.getInt("passenger_id");
                        tno = result.getString("passenger_first_name");
                        pname = result.getString("passenger_last_name");
                        mob = result.getString("passenger_father_name");
                        add = result.getString("passenger_mother_name");
                        agE = result.getString("DOB");
                    
                          souce = result.getString("EmailID");
                          des = result.getString("MobileNo");
                          fare = result.getString("occupation");
                          time = result.getString("AadharNo");
                          cno = result.getString("state");
                          ctyp = result.getString("district");
                          styp = result.getString("city");
                          sno = result.getString("pin");
                          fp = result.getString("age");
                          fi = result.getString("address");
                          fi1 = result.getString("Gender");
                          
                       Tname.setText(pname);
                        Tdob.setText(agE);
                         Tstate.setText(cno);
                          Tdistrict.setText(ctyp);
                           Temail.setText(souce);
                            Tcity.setText(styp);
                             Toccupation.setText(fare);
                              Taddress.setText(fi);
                             //  passengerlabel.setText(resid.toString());
                               //JOptionPane.showInputDialog(this, "Enter your id :", JOptionPane.INFORMATION_MESSAGE);
                         
                      
                      String sql1 = "SELECT img FROM `image1` WHERE pass_id = '"+passid.getText()+"' ;";
           

           Statement sm = con.createStatement();
            ResultSet resultSet;
                    resultSet = sm.executeQuery(sql1);

            if (resultSet.next()) {
                // Retrieve the image data from the database
                Blob blob = resultSet.getBlob("img");
                byte[] imageData = blob.getBytes(1, (int) blob.length());

                // Convert byte array to Image
                ByteArrayInputStream bis = new ByteArrayInputStream(imageData);
                Image image = ImageIO.read(bis);
                System.out.print(image);
                // Set the image to the JLabel
                var imageIcon = new ImageIcon(image);
                i2=new ImageIcon(imageIcon.getImage().getScaledInstance(200,200, WIDTH));
                photolabel.setIcon(i2);
            }
            setVisible(true);
            
                    }
                     }
            catch(Exception ex){
                ex.printStackTrace();
            }
        
        
        
    }//GEN-LAST:event_ViewActionPerformed

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameActionPerformed

    private void TdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdobActionPerformed

    private void TemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemailActionPerformed

    private void TdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdistrictActionPerformed

    private void TaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Project_Main  u = new Project_Main();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
                new Profile().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genderlabel;
    private javax.swing.JTextField Taddress;
    private javax.swing.JTextField Tcity;
    private javax.swing.JTextField Tdistrict;
    private javax.swing.JTextField Tdob;
    private javax.swing.JTextField Temail;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Toccupation;
    private javax.swing.JTextField Tstate;
    private javax.swing.JButton View;
    private javax.swing.JTextField genderlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobilenolabel;
    private javax.swing.JLabel occupationlabel;
    private javax.swing.JTextField passid;
    private javax.swing.JLabel photolabel;
    // End of variables declaration//GEN-END:variables
}
