/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

/**
 *
 * @author KARTHI
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.sql.*;
import train.Project_Main;
import java.time.Clock;
import java.util.logging.Level;
import java.util.logging.Logger;
import train.Database_1;
public class Reserve_Train extends javax.swing.JFrame {

    /**
     * Creates new form Reserve_Train
     */
    JPanel ps;
     String Date;
   int y23,y72 = 0;
   String h12;
   String fare;
   String fe1;
   int Seatno=0;
   String fe;
    String passname;
    String coachno;
    String acornonac;
    String sleeornonsleep;
    String foodyesorno;
    String foods;
    String passengername;
    String address;
    String Mobileno;
    Connection con;
    Statement statement;
    ResultSet result;
    String Age;
   // String Date;
    String trainno;
    String From;
    String to;
     String f;
    String Time;
    String id;
    int amount;
    int s;
    Integer u1 = 0;
    int a1=0,a2=0,a3=0,a4=0,b1=0,b2=0,b3=0,b4=0,c1=0,c2=0,c3=0,c4=0,d1=0,d2=0,d3=0,d4=0;
    
    public Reserve_Train() {
        initComponents();
    }
    private boolean validatePhone(){
        String val = mobileno.getText().toString().trim();
        String validation = "^[0-9]{10}$";
        if(!val.matches(validation)){
                JOptionPane.showMessageDialog(this, "Only 10 digits number is valid!", "PhoneNo Error", HEIGHT);
                return false;
        }
        else if(val.isEmpty()){
            JOptionPane.showMessageDialog(this, "Field can't be empty", "PhoneNo Error", HEIGHT);
            return false;
        }
        else
        {
            return true;
        }
        }
     private boolean validateAddress(){
        String val = Address.getText().toString().trim();
        String validation = "^[#.0-9a-zA-Z\\s,-]+$";
        if(val.isEmpty()){
            JOptionPane.showMessageDialog(this, "Field can't be empty", "AddressError", HEIGHT);
            return false;
        }
        else if(!val.matches(validation)){
            JOptionPane.showMessageDialog(this,"Invalid format. Format should be #1, North Street, Chennai - 11");
            return false;
        }
        else
        {
            return true;
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mobileno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Passname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        Payment = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TrainCompartment = new javax.swing.JLabel();
        destination = new javax.swing.JTextField();
        aircond = new javax.swing.JRadioButton();
        Nonaccon = new javax.swing.JRadioButton();
        TrainNo = new javax.swing.JComboBox<String>();
        NonSleeper = new javax.swing.JRadioButton();
        Sleeper = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        Yes = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CoachNo = new javax.swing.JComboBox<>();
        Submit = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("RESERVATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 0, 300, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("PASSENGER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 230, 50);

        mobileno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoActionPerformed(evt);
            }
        });
        getContentPane().add(mobileno);
        mobileno.setBounds(320, 190, 260, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ADDRESS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 130, 140, 50);

        Passname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Passname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassnameActionPerformed(evt);
            }
        });
        getContentPane().add(Passname);
        Passname.setBounds(320, 80, 260, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("MOBILE NUMBER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 210, 50);

        Address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        getContentPane().add(Address);
        Address.setBounds(320, 130, 260, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("AGE ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 140, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("TRAIN NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 280, 190, 60);

        age.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(320, 240, 260, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("FROM ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 340, 150, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("TO ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 400, 140, 40);

        from.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        getContentPane().add(from);
        from.setBounds(320, 340, 260, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("DATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 500, 160, 40);

        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date);
        date.setBounds(320, 500, 260, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("TIME");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 560, 140, 40);

        time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(time);
        time.setBounds(320, 550, 260, 40);

        Payment.setBackground(new java.awt.Color(0, 255, 204));
        Payment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Payment.setText("Payment");
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });
        getContentPane().add(Payment);
        Payment.setBounds(640, 630, 180, 40);

        Back.setBackground(new java.awt.Color(255, 0, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(110, 630, 160, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(890, 630, 170, 40);

        TrainCompartment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TrainCompartment.setText("COACH NUMBER");
        getContentPane().add(TrainCompartment);
        TrainCompartment.setBounds(30, 450, 210, 40);

        destination.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationActionPerformed(evt);
            }
        });
        getContentPane().add(destination);
        destination.setBounds(320, 390, 260, 50);

        aircond.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aircond.setText("AC Coach");
        getContentPane().add(aircond);
        aircond.setBounds(710, 110, 120, 40);

        Nonaccon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Nonaccon.setText("Non-AC Coach");
        getContentPane().add(Nonaccon);
        Nonaccon.setBounds(890, 120, 150, 30);

        String y;
        try
        {
            String query="SELECT train_number FROM train_information;";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
            statement=con.createStatement();
            result=statement.executeQuery(query);
            System.out.println(result);
            while(result.next())
            {
                s = result.getInt("train_number");
                y = String.valueOf(s);
                TrainNo.addItem(y);

            }

        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        TrainNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainNoActionPerformed(evt);
            }
        });
        getContentPane().add(TrainNo);
        TrainNo.setBounds(320, 290, 260, 40);

        NonSleeper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NonSleeper.setText("Non-Sleeper");
        getContentPane().add(NonSleeper);
        NonSleeper.setBounds(910, 220, 130, 30);

        Sleeper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sleeper.setText("Sleeper");
        getContentPane().add(Sleeper);
        Sleeper.setBounds(710, 220, 98, 30);

        No.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        No.setText("No");
        getContentPane().add(No);
        No.setBounds(920, 340, 98, 30);

        Yes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Yes.setText("Yes");
        getContentPane().add(Yes);
        Yes.setBounds(720, 340, 98, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText(" Coach Type");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 70, 160, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Seat Type");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(720, 160, 130, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Food Pantry");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(720, 280, 140, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("If Yes, Enter your Food Items");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(730, 390, 330, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(730, 440, 340, 150);

        CoachNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CoachNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3", "A4", "B1", "B2", "B3", "B4", "B5", "C1", "C2", "C3", "C4", "D1", "D2", "D3", "D4", "D5" }));
        getContentPane().add(CoachNo);
        CoachNo.setBounds(320, 450, 260, 40);

        Submit.setBackground(new java.awt.Color(0, 102, 51));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(390, 630, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenoActionPerformed
        // TODO add your handling code here:
        mobileno.setText(Mobileno);
    }//GEN-LAST:event_mobilenoActionPerformed

    private void PassnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassnameActionPerformed
        // TODO add your handling code here:
        Passname.setText(passname);
    }//GEN-LAST:event_PassnameActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
        age.setText(Age);
    }//GEN-LAST:event_ageActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fromActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
        Address.setText(address);
    }//GEN-LAST:event_AddressActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TrainNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainNoActionPerformed
        // TODO add your handling code here
        String y;
        try
{
    String query="SELECT train_number FROM train_information;";
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
			statement=con.createStatement();
			result=statement.executeQuery(query);
                        System.out.println(result);
	while(result.next())
	{
             s = result.getInt("train_number");
             y = String.valueOf(s);
                TrainNo.addItem(y);
                
		
	}
       
        
	
}
catch(SQLException e)
{
	e.printStackTrace();
}

        
    }//GEN-LAST:event_TrainNoActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        // TODO add your handling code here:
         Payment y = new Payment();
         y.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_PaymentActionPerformed

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        // Integer u1 = 0;
        h12 =  (String)TrainNo.getSelectedItem();
        System.out.println(h12);
       int y23 = Integer.parseInt(h12);
       System.out.print(y23);
        String query1="SELECT * FROM train_information WHERE train_number = '"+y23+"' ";
        Database_1 g = new Database_1();
        ResultSet f1 = g.select(query1);
        
        try {
            while(f1.next())
            {
               
                u1 = f1.getInt("price");
                 fe = f1.getString("source");
                fe1 = f1.getString("destination");
                from.setText(fe);
               destination.setText(fe1);
            }
             
 
        } catch (SQLException ex) {
            Logger.getLogger(Reserve_Train.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showConfirmDialog(this, "your fare is " + u1);
       // Payment u = new Payment();
       // u.getAmount(u1.toString());
       
       Seatno = 0;
               passengername = Passname.getText();
               address = Address.getText();
               Mobileno  = mobileno.getText();
               boolean val1 = validatePhone();
               boolean val2 = validateAddress();
               trainno =TrainNo.getSelectedItem().toString();
               Age = age.getText();
               
               if(val1 == true && val2 == true)
               {
               coachno = (String) CoachNo.getSelectedItem();
               int y =  CoachNo.getSelectedIndex();
               {
                   if(y == 1)
                   {    
                        if(a1 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                a1++;
                       Seatno = a1;
                        }
                   }
                   
                    if(y == 2)
                   {    
                        if(a2 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                a2++;
                       Seatno = a2;
                        }
                   }
                    
                     if(y == 3)
                   {    
                        if(a3 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                a3++;
                       Seatno = a3;
                        }
                   }
                     
                      if(y == 4)
                   {    
                        if(a4 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                a4++;
                       Seatno = a4;
                        }
                   }
                      
                       if(y == 5)
                   {    
                        if(b1 == 0)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                b1++;
                       Seatno = b1;
                        }
                   }
                       
                        if(y == 6)
                   {    
                        if(b2 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                b2++;
                       Seatno = b2;
                        }
                   }
                        
                         if(y == 7)
                   {    
                        if(b3 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                b3++;
                       Seatno = b3;
                        }
                   }
                         
                         
                          if(y == 8)
                   {    
                        if(b4 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                b4++;
                       Seatno = b4;
                        }
                   }
                          
                           if(y == 9)
                   {    
                        if(c1 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                c1++;
                       Seatno = c1;
                        }
                   }
                           
                            if(y == 10)
                   {    
                        if(c2 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                c2++;
                       Seatno = c2;
                        }
                   }
                            
                   if(y == 11)
                   {    
                        if(c3 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                c3++;
                       Seatno = c3;
                        }
                   }

                   if(y == 12)
                   {    
                        if(c4 == 30)
                                JOptionPane.showConfirmDialog(this, "THIS COACH IS FULL TRY ANOTHER", "Error", JOptionPane.ERROR_MESSAGE);
                        else
                        {
                                c4++;
                       Seatno = c4;
                        }
                   }
                    }
         
               if(aircond.isSelected())
                   acornonac = "AC Coach";
               else
                   acornonac = "Non-Ac Coach";
               if(Sleeper.isSelected())
                   sleeornonsleep = "Sleeper Seats";
               else
                    sleeornonsleep = "Ordinary Seats";
               if(Yes.isSelected())
               {
                   foodyesorno = "Yes";
                   foods = jTextArea1.getText();
               }
               else
               {
                   foodyesorno = "NO";
                   foods = "Nill";
               }
               System.out.print("SEAT NUMBER IS :" + Seatno);
               to = destination.getText();
               fare = u1.toString();
               Time = time.getText();
               Date = date.getText();
               IDgen y2 = new IDgen();
                f = y2.Captcha();
              y72 = Integer.parseInt(f);
             //  u.getId(f);
               String Query = "insert into reserved values('"+y72+"','"+trainno+"','"+passengername+"','"+Mobileno+"','"+address+"','"+Age+"','"+From+"','"+to+"','"+fare+"','"+Time+"','"+Date+"','"+coachno+"','"+acornonac+"','"+sleeornonsleep+"','"+Seatno+"','"+foodyesorno+"','"+foods+"')";
               Database_1 j = new Database_1();
              int t=j.execute(Query);		
		   if(t==0)
		   {
			   JOptionPane.showMessageDialog(this, "Unable To Insert Please try Again Later ","Error",JOptionPane.ERROR_MESSAGE);	   
		   }
		   else
			   JOptionPane.showMessageDialog(this, "OPERATION SUCESSFUL your Ticket id :" +y72+"Dont Forget","Error",JOptionPane.INFORMATION_MESSAGE);	   
               }
               else
                   JOptionPane.showMessageDialog(this, "Unable To Insert Invalid  ","Error",JOptionPane.ERROR_MESSAGE);	   
    }//GEN-LAST:event_SubmitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Project_Main u = new Project_Main();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserve_Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserve_Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserve_Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserve_Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Reserve_Train().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> CoachNo;
    private javax.swing.JRadioButton No;
    private javax.swing.JRadioButton NonSleeper;
    private javax.swing.JRadioButton Nonaccon;
    private javax.swing.JTextField Passname;
    private javax.swing.JButton Payment;
    private javax.swing.JRadioButton Sleeper;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel TrainCompartment;
    javax.swing.JComboBox<String> TrainNo;
    private javax.swing.JRadioButton Yes;
    private javax.swing.JTextField age;
    private javax.swing.JRadioButton aircond;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField date;
    private javax.swing.JTextField destination;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mobileno;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables

    
     String getId()
    {
        id = f;
        return id;
    }
    int getAmount()
    {
       amount = u1 ;
        return amount;
    }

    
}
