/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

//import java.beans.Statement;
import com.mycompany.edittraininfo.Employee;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author myash
 */
public class ReservesStatus extends javax.swing.JFrame {
Statement stmt;
Connection con;
ResultSet result;



    /**
     * Creates new form ReservesStatus
     */
    public ReservesStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usercount = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ReserveTicket ID", "Passenger Name", "Mobile Number", "Address", "Age", "From", "To", "Fare", "Time", "Coach Number", "Coach Type", "Seat Type", "Seat Number", "Food Pantry", "Food Items"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 190, 1438, 402);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reservation Status");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(478, 6, 271, 46);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("Click Here To View the Reservation Status");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 93, 593, 51);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Enter ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(734, 93, 220, 51);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Reserved Members in Total");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1010, 40, 240, 30);
        getContentPane().add(usercount);
        usercount.setBounds(1300, 40, 80, 30);
        getContentPane().add(cost);
        cost.setBounds(1300, 90, 80, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Total Cost");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1090, 86, 130, 30);

        Back.setBackground(new java.awt.Color(255, 0, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(30, 20, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
         try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
        } catch (SQLException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        }
         jTable1.setBackground(new java.awt.Color(255,204,0));
         jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "reserveid",
                "train_number","passenger_name","mobile_number","adddress","age", "From", "To" ,"Fare","Time","Coach_number","Coach_type","Seat_type","Seat_number","Food_pantry","fooditems"
            }
        ));
         jTable1.setGridColor(new java.awt.Color(153, 255, 255));
         jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
         jTable1.setRowHeight(100);
         jTable1.setShowHorizontalLines(true);
        
            DefaultTableModel tbl=(DefaultTableModel)  jTable1.getModel();
            tbl.setRowCount(0);
            String query = "SELECT * from reserved";
            int y = 0;
            int u;
            int c = 0;
            try {
                stmt = con.createStatement();
                result = stmt.executeQuery(query);
                    String pname,souce,des,arr,dept,mob,add,agE,fare,tno,time,cno,ctyp,styp,sno,fp,fi;
                    Integer resid;
                    while(result.next()){
                        resid = result.getInt("reserveid");
                        tno = result.getString("train_number");
                        pname = result.getString("passenger_name");
                        mob = result.getString("mobile_number");
                        add = result.getString("address");
                        agE = result.getString("age");
                    
                          souce = result.getString("From");
                          des = result.getString("To");
                          fare = result.getString("Fare");
                          time = result.getString("Time");
                          cno = result.getString("Coach_number");
                          ctyp = result.getString("Coach_type");
                          styp = result.getString("Seat_type");
                          sno = result.getString("Seat_number");
                          fp = result.getString("Food_pantry");
                          fi = result.getString("fooditems");
                          u = Integer.parseInt(fare);
                          ++c;
                          y += u;
                        String [] rowData={resid.toString(),tno,pname,mob,add,agE,souce,des,fare,time,cno,ctyp,styp,sno,fp,fi};
                        tbl.addRow(rowData);
                    }
                     }
            catch(Exception ex){
                ex.printStackTrace();
            }
            String h = String.valueOf(c);
        usercount.setText(h);
        String h1 = String.valueOf(y);
        cost.setText(h1);
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
       AdminStatus i = new AdminStatus();
       i.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservesStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservesStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel cost;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel usercount;
    // End of variables declaration//GEN-END:variables
}
