/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

/**
 *
 * @author KARTHI
 */

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;



import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.Connection;
import java.awt.*;
import java.util.Random;
import javax.swing.JOptionPane;
public class Ticket_Generation extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_Generation
     */
      int ch;
   String r;
 String y12;
   Connection con;
   ResultSet result,result1;
   Statement statement1;
    public Ticket_Generation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        platform = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        REserveid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        createpdf = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TRAIN NO  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 240, 140, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SEAT NO :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 450, 120, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("TRAIN NAME ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 180, 180, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("PLATFORM NO ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 330, 190, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("COACH NO ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 400, 210, 40);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(570, 182, 260, 40);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(570, 242, 260, 40);

        platform.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(platform);
        platform.setBounds(570, 322, 260, 40);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(570, 392, 260, 40);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(570, 452, 260, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Enter Your Reserve Id to Generate your ticket");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 110, 520, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1030, 120, 220, 40);
        getContentPane().add(REserveid);
        REserveid.setBounds(720, 120, 260, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Click To generate your Ticket into PDF Format");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 530, 530, 40);

        createpdf.setBackground(new java.awt.Color(255, 51, 255));
        createpdf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createpdf.setText("Download");
        createpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createpdfActionPerformed(evt);
            }
        });
        getContentPane().add(createpdf);
        createpdf.setBounds(770, 540, 230, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("TICKET GENERATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 30, 850, 60);

        Back.setBackground(new java.awt.Color(255, 0, 0));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(60, 50, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
         r = REserveid.getText();
        ch = Integer.parseInt(r);
       
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
             Statement statement;
             int y1;
            statement = con.createStatement();
              statement1 = con.createStatement();
             String query = "select * from reserved where reserveid = '"+Integer.parseInt(REserveid.getText())+"'";
           
             result=statement.executeQuery(query);
             Random random = new Random();
           
           // Define the range of characters allowed in OTP (here, using only digits)
           String numbers = "0123456789";
           
           StringBuilder otp = new StringBuilder();
           for (int i = 0; i < 1; i++) {
               // Get a random index from 0 to numbers.length() - 1
               int index = random.nextInt(numbers.length());
               
               // Append the character at the randomly generated index to the OTP
               otp.append(numbers.charAt(index));
           }
           String otp1 = otp.toString();
            while(result.next())
            {
               jTextField2.setText(result.getString("train_number"));
               jTextField4.setText(result.getString("Coach_number"));
               jTextField5.setText(result.getString("Seat_number"));
              platform.setText(otp1);
               y1 = Integer.parseInt(result.getString("train_number"));
               
                String query1 = "select * from train_information where train_number = '"+y1+"'";
                result1 = statement1.executeQuery(query1);
                while(result1.next())
                {
                    y12 = result1.getString("train_name");
                   jTextField1.setText(result1.getString("train_name")); 
                }
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createpdfActionPerformed
        // TODO add your handling code here:
       String jdbcURL = "jdbc:mysql://localhost:3306/train_db";
        String username = "root";
        String password = "";

        try {
            // Establishing a database connection
            Connection connection = DriverManager.getConnection(jdbcURL, username, password);
            Statement statement = connection.createStatement();
             String y = platform.getText();

            // Execute a query to fetch data from the database
            ResultSet resultSet = statement.executeQuery("select * from reserved where reserveid = '"+Integer.parseInt(REserveid.getText())+"'");

            // Creating a PDF document using iText
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Ramesh.pdf"));
            document.open();

            // Adding database data to the PDF document
            while (resultSet.next()) {
                int column1Data = resultSet.getInt("reserveid");
                String column2Data = resultSet.getString("train_number");
                  String column3Data = resultSet.getString("passenger_name");
                String column4Data = resultSet.getString("mobile_number");
                  String column5Data = resultSet.getString("address");
                String column6Data = resultSet.getString("age");
                  String column7Data = resultSet.getString("From");
                String column8Data = resultSet.getString("To");
                  String column9Data = resultSet.getString("Fare");
                String column10Data = resultSet.getString("Time");
                  String column11Data = resultSet.getString("Coach_number");
                String column12Data = resultSet.getString("Coach_type");
                  String column13Data = resultSet.getString("Seat_type");
                String column14Data = resultSet.getString("Seat_number");
                  String column15Data = resultSet.getString("Food_pantry");
                String column16Data = resultSet.getString("fooditems");
                // Adding data to the PDF document
                document.add(new Paragraph("-----------------Online Train Ticket Reservation Sytem-------------------------"));
                 document.add(new Paragraph(">>>>>>>>>>>>>>>>>     Train Ticket     <<<<<<<<<<<<<<<<<<<"));
                
               // document.add(new Paragraph("Reserved id : " + column1Data));
                document.add(new Paragraph("Train Number: " + column2Data));
                document.add(new Paragraph("Train Name: " + y12));
                document.add(new Paragraph("PlatForm Number : " + y));
                document.add(new Paragraph("Passenger Name: " + column3Data));
                document.add(new Paragraph("Mobile Number: " + column4Data));
              //  document.add(new Paragraph("Address: " + column5Data));
                document.add(new Paragraph("Age: " + column6Data));
                document.add(new Paragraph("From : " + column7Data));
                document.add(new Paragraph("To : " + column8Data));
                document.add(new Paragraph("Fare: " + column9Data));
                document.add(new Paragraph("Time : " + column10Data));
                document.add(new Paragraph("Coach Number : " + column11Data));
                document.add(new Paragraph("Coach_Type : " + column12Data));
                document.add(new Paragraph("Seat_Number : " + column13Data));
                document.add(new Paragraph("Seat_Type : " + column14Data));
                document.add(new Paragraph("Food Pantry: " + column15Data));
              //  document.add(new Paragraph("Column 16: " + column16Data));
                
                document.add(new Paragraph("-------------------------------------------"));
            }

            // Closing resources
            document.close();
            resultSet.close();
            statement.close();
            connection.close();

           // System.out.println("PDF created successfully.");
            JOptionPane.showConfirmDialog(this, "PDF created successfully.", "Success",JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
        }
       // u.setVisible(true);
    }//GEN-LAST:event_createpdfActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Project_Main u = new Project_Main();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_Generation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_Generation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_Generation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_Generation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_Generation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField REserveid;
    private javax.swing.JButton createpdf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField platform;
    // End of variables declaration//GEN-END:variables
}
