/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author myash
 */
public class Ticket_Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_Cancellation
     */
   // ResultSet result;
      Connection con;
  ResultSet result,result1;
   Statement statement1,statement;
   String y12;
    public Ticket_Cancellation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ReseID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TName = new javax.swing.JTextField();
        Tage = new javax.swing.JTextField();
        Ttrainno = new javax.swing.JTextField();
        Tseatno = new javax.swing.JTextField();
        Tseatcoach = new javax.swing.JTextField();
        Ttime = new javax.swing.JTextField();
        Ttrainname = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        TDate1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter the Reserved ID To Cancel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 280, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Ticket Cancellation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(458, 27, 462, 35);

        ReseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReseIDActionPerformed(evt);
            }
        });
        getContentPane().add(ReseID);
        ReseID.setBounds(400, 120, 300, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 240, 150, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 310, 120, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Seat Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 250, 160, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Seat Coach ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 330, 130, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Train Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 400, 130, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Time");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 400, 50, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Train Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(760, 190, 130, 25);

        TName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNameActionPerformed(evt);
            }
        });
        getContentPane().add(TName);
        TName.setBounds(260, 250, 170, 30);
        getContentPane().add(Tage);
        Tage.setBounds(260, 320, 170, 30);
        getContentPane().add(Ttrainno);
        Ttrainno.setBounds(260, 400, 170, 30);
        getContentPane().add(Tseatno);
        Tseatno.setBounds(780, 252, 160, 30);
        getContentPane().add(Tseatcoach);
        Tseatcoach.setBounds(780, 330, 160, 30);
        getContentPane().add(Ttime);
        Ttime.setBounds(780, 400, 160, 30);
        getContentPane().add(Ttrainname);
        Ttrainname.setBounds(920, 190, 170, 30);

        Search.setBackground(new java.awt.Color(255, 255, 0));
        Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(795, 123, 140, 30);

        Back.setBackground(new java.awt.Color(0, 255, 51));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(280, 490, 200, 40);

        Cancel.setBackground(new java.awt.Color(255, 0, 0));
        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(580, 490, 200, 40);
        getContentPane().add(TDate1);
        TDate1.setBounds(470, 192, 170, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Date of Travel ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 200, 130, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReseIDActionPerformed

    private void TNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNameActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        String h = ReseID.getText();
        int y = Integer.parseInt(h);
        String query = "delete from reserved where reserveid = '"+Integer.parseInt(ReseID.getText())+"'";
          try {
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
              statement = con.createStatement();
              statement1 = con.createStatement();
             int y1 = statement.executeUpdate(query);
             JOptionPane.showConfirmDialog(this, "Returned Successfully", "Success",JOptionPane.INFORMATION_MESSAGE);
             JOptionPane.showConfirmDialog(this, "Your Fare is sent to your account within 1 or 2 days", "Success",JOptionPane.INFORMATION_MESSAGE);
          } catch (SQLException ex) {
              Logger.getLogger(Ticket_Cancellation.class.getName()).log(Level.SEVERE, null, ex);
          }
         
        
    }//GEN-LAST:event_CancelActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String h = ReseID.getText();
        int y = Integer.parseInt(h);
        String query = "select * from reserved where reserveid = '"+Integer.parseInt(ReseID.getText())+"'";
        
        
        
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
             Statement statement;
             int y1;
            statement = con.createStatement();
              statement1 = con.createStatement();
             //String query = "select * from reserved where reserveid = '"+Integer.parseInt(REserveid.getText())+"'";
           
             result=statement.executeQuery(query);
            while(result.next())
            {
                TName.setText(result.getString("passenger_name"));
                Tage.setText(result.getString("age"));
                Tseatno.setText(result.getString("Seat_number"));
                Ttrainno.setText(result.getString("train_number"));
                Tseatcoach.setText(result.getString("Coach_number"));
                Ttime.setText(result.getString("Time"));
               TDate1.setText(result.getString("Date"));
               Ttime.setText(result.getString("Time"));
               y1 = Integer.parseInt(result.getString("train_number"));
               
                String query1 = "select * from train_information where train_number = '"+y1+"'";
                result1 = statement1.executeQuery(query1);
                while(result1.next())
                {
                    y12 = result1.getString("train_name");
                   Ttrainname.setText(result1.getString("train_name")); 
                }
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Project_Main i = new Project_Main();
        i.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField ReseID;
    private javax.swing.JButton Search;
    private javax.swing.JTextField TDate1;
    private javax.swing.JTextField TName;
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tseatcoach;
    private javax.swing.JTextField Tseatno;
    private javax.swing.JTextField Ttime;
    private javax.swing.JTextField Ttrainname;
    private javax.swing.JTextField Ttrainno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
