/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;

import com.mycompany.edittraininfo.Employee;
import java.sql.Connection;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.sql.Statement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author KARTHI
 */
public class Update_Traininfo extends javax.swing.JFrame {
Statement statement;
Connection con;
int s;
ResultSet result;
String tno;
String trainname;
String from;
String to;
String arr;
String depttu;
String price;

    /**
     * Creates new form Update
     */
    public Update_Traininfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Destination = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Arrival = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Departure = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Cost = new javax.swing.JTextField();
        Logout = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        TrainNo = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 1200));
        setName(""); // NOI18N
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("UPDATE TRAIN INFORMATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 10, 560, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("TRAIN NAME ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 140, 180, 50);

        Tname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Tname);
        Tname.setBounds(560, 140, 260, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TRAIN NO  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 180, 140, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("FROM ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 250, 150, 50);

        From.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(From);
        From.setBounds(560, 260, 260, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("TO ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 320, 140, 40);

        Destination.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Destination);
        Destination.setBounds(560, 320, 260, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("ARRIVAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 360, 190, 60);

        Arrival.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Arrival);
        Arrival.setBounds(560, 372, 260, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("DEPATURE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 426, 160, 40);

        Departure.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Departure);
        Departure.setBounds(560, 422, 260, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("COST");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 480, 190, 40);

        Cost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Cost);
        Cost.setBounds(560, 482, 260, 40);

        Logout.setBackground(new java.awt.Color(255, 0, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setText("BACK");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(310, 560, 160, 40);

        Submit.setBackground(new java.awt.Color(0, 102, 51));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(520, 560, 170, 40);

        Reset.setBackground(new java.awt.Color(255, 255, 0));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset);
        Reset.setBounds(750, 560, 170, 40);

        TrainNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        String y;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
            statement=con.createStatement();
            String query="SELECT train_number FROM train_information;";
            result=statement.executeQuery(query);
            while(result.next())
            {
                s = result.getInt("train_number");
                y = String.valueOf(s);
                TrainNo.addItem(y);

            }

        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        getContentPane().add(TrainNo);
        TrainNo.setBounds(560, 202, 260, 40);

        jLabel9.setText("Online Train Reservation System");
        jLabel9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel9PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1050, 80, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        String def = " ";
        Tname.setText(def);
       // TrainNo.setText(def);
        From.setText(def);
        Destination.setText(def);
        Arrival.setText(def);
        Departure.setText(def);
        Cost.setText(def);
    }//GEN-LAST:event_ResetActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "OPERATION SUCESSFUL ","Error",JOptionPane.INFORMATION_MESSAGE);
         Employee r = new Employee();
         this.setVisible(false);
         r.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
       trainname = Tname.getText();
       tno = (String) TrainNo.getSelectedItem();
       
       int ch=Integer.parseInt(""+TrainNo.getSelectedItem());
       from = From.getText();
       to = Destination.getText();
       arr = Arrival.getText();
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
       LocalTime time = LocalTime.parse(arr,formatter);
      // Time res = arr.
       depttu = Departure.getText();
        LocalTime time1 = LocalTime.parse(depttu,formatter);
       price = Cost.getText();
       
       String Query  ="update train_information set train_number ='"+tno+"',train_name = '"+trainname+"',source = '"+from+"',destination = '"+to+"',arrival = '"+time+"',departure = '"+time1+"',price = '"+price+"' where train_number="+ch;  
       Database_1 u = new Database_1();
       int ur = u.execute(Query);
       if(ur==0)
		   {
			   JOptionPane.showMessageDialog(this, "Unable To Insert Please try Again Later","Error",JOptionPane.ERROR_MESSAGE);	   
		   }
		   else
			   JOptionPane.showMessageDialog(this, "OPERATION SUCESSFUL ","Error",JOptionPane.INFORMATION_MESSAGE);	   
    }//GEN-LAST:event_SubmitActionPerformed

    private void jLabel9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel9PropertyChange
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jLabel9PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Traininfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Traininfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Arrival;
    private javax.swing.JTextField Cost;
    private javax.swing.JTextField Departure;
    private javax.swing.JTextField Destination;
    private javax.swing.JTextField From;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField Tname;
    private javax.swing.JComboBox<String> TrainNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
