/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package train;
//
import com.mycompany.edittraininfo.Employee;
import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author myash
 */
public class UserStatus extends javax.swing.JFrame {
    Statement stmt;
    Connection con;
    ResultSet result;
File Limage;
    /**
     * Creates new form UserStatus
     */
    public UserStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        View = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usercount = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Passenger_id", "Passenger_first_name", "Passenger_last_name", "Passenger_father_name", "Passenger_mother_name", "DOB", "EmailID", "MobileNo", "occupation", "AadharNo", "state", "district", "city", "pin", "age", "address", "Gender"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(2, 140, 2320, 402);

        View.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        View.setText("Click To View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        getContentPane().add(View);
        View.setBounds(460, 90, 190, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Users  List");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 20, 190, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Users Count");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(810, 30, 110, 30);

        usercount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(usercount);
        usercount.setBounds(950, 30, 90, 30);

        Back.setBackground(new java.awt.Color(255, 0, 51));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(30, 50, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train_db","root","");
        } catch (SQLException ex) {
            Logger.getLogger(Status.class.getName()).log(Level.SEVERE, null, ex);
        }
         jTable1.setBackground(new java.awt.Color(255,204,0));
         jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "passenger_id",
                "passenger_first_name","passenger_last_name","passenger_father_name","passenger_mother_name","DOB", "EmailID", "MobileNo" ,"occupation","AadharNo","state","district","city","pin","age","address","Gender"
            }
        ));
         jTable1.setGridColor(new java.awt.Color(153, 255, 255));
         jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
         jTable1.setRowHeight(50);
         jTable1.setShowHorizontalLines(true);
        
            DefaultTableModel tbl=(DefaultTableModel)  jTable1.getModel();
            tbl.setRowCount(0);
            int c = 0;
            String query = "SELECT * from user_info";
            try {
                stmt = con.createStatement();
                result = stmt.executeQuery(query);
                    String pname,souce,des,arr,dept,mob,add,agE,fare,tno,time,cno,ctyp,styp,sno,fp,fi,fi1;
                    Integer resid;
                    
                    while(result.next()){
                        resid = result.getInt("passenger_id");
                        tno = result.getString("passenger_first_name");
                        pname = result.getString("passenger_last_name");
                        mob = result.getString("passenger_father_name");
                        add = result.getString("passenger_mother_name");
                        agE = result.getString("DOB");
                    
                          souce = result.getString("EmailID");
                          des = result.getString("MobileNo");
                          fare = result.getString("occupation");
                          time = result.getString("AadharNo");
                          cno = result.getString("state");
                          ctyp = result.getString("district");
                          styp = result.getString("city");
                          sno = result.getString("pin");
                          fp = result.getString("age");
                          fi = result.getString("address");
                          fi1 = result.getString("Gender");
                            ++c;  
                        String [] rowData={resid.toString(),tno,pname,mob,add,agE,souce,des,fare,time,cno,ctyp,styp,sno,fp,fi,fi1};
                        tbl.addRow(rowData);
                    }
                     }
            catch(Exception ex){
                ex.printStackTrace();
            }
        String h = String.valueOf(c);
        usercount.setText(h);
        
    }//GEN-LAST:event_ViewActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
       AdminStatus i = new AdminStatus();
       i.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed
                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel usercount;
    // End of variables declaration//GEN-END:variables
}
